name: Notificar feriados

on:
  schedule:
    - cron: '0 10 * * *'  # Todos los días a las 10:00 UTC (aquí se puede ajustar)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          CALENDARIFIC_API_KEY: ${{ secrets.CALENDARIFIC_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
